### ISSUE TITLE
Volume server hangs on some volumes

### ISSUE THREAD

**Issue by LuckyFrost** [chrislusf/weed-fs#3459]
**Describe the bug**
Request like 
`curl "http://xxx.xxx.xxx.xxx:8080/3064,015abe1331dff8f7?readDeleted=true"` 
can hang forever in unknown situations without any errors

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".

`/opt/weed -logdir=/var/log/weed volume -ip=x.x.x.x -mserver=x.x.x.x:9333,y.y.y.y:9333,z.z.z.z:9333 -whiteList=x.x.x.x,y.y.y.y,z.z.z.z,n.n.n.n -dir=/mnt/sda,/mnt/sdb,/mnt/sdc,/mnt/sdd,/mnt/sde,/mnt/sdf,/mnt/sdg,/mnt/sdh -dir.idx=/srv/vweed -disk=hdd -compactionMBps=2000 -dataCenter=dc1 -rack=rack1 -max=0,0,0,0,0,0,0,0`

`/opt/weed -logdir=/var/log/weed master -ip=x.x.x.x -mdir=/srv/mweed/  -volumeSizeLimitMB=20480 -volumePreallocate -defaultReplication=010 -peers=x.x.x.x:9333,y.y.y.y:9333,z.z.z.z:9333 -metrics.address=http://1.2.3.4:9091 -whiteList=x.x.x.x,y.y.y.y,z.z.z.z -raftHashicorp`

- OS version
Oracle Linux Server 8.6
- output of `weed version`
`version 8000GB 3.22 fa4d0093e17f710c3da00545022646cb96a6fd98 linux amd64`

**Expected behavior**
1) No duplicates
2) Timeout/error in case of downstream storage problems
3)  Correct work in such situations?

**Additional context**
Found that this volume (and possibly others) is duplicated
./sdd/xxx_3064.dat
./sdd/xxx_3064.vif
./sde/xxx_3064.vif
./sde/xxx_3064.dat

**Comment by LuckyFrost** [comment]
[kill3volume.txt](https://github.com/seaweedfs/seaweedfs/files/9372408/kill3volume.txt)

**Comment by LuckyFrost** [comment]
Removed duplicate volumes  (actually, their md5 is different from their other copies) - stopped hanging.
Returned one broken volume out of many - it began to hang, but not forever, but for 30 seconds, and the volume server gives an error
```
Aug 18 05:34:21  seaweedfs-volume[3039922]: 2022/08/18 05:34:21 http: panic serving 192.168.0.82:62368: runtime error: makeslice: len out of range
Aug 18 05:34:21  seaweedfs-volume[3039922]: goroutine 3175 [running]:
Aug 18 05:34:21  seaweedfs-volume[3039922]: net/http.(*conn).serve.func1()
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/usr/local/go/src/net/http/server.go:1850 +0xbf
Aug 18 05:34:21  seaweedfs-volume[3039922]: panic({0x1fa9900, 0x2915ee0})
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/usr/local/go/src/runtime/panic.go:890 +0x262
Aug 18 05:34:21  seaweedfs-volume[3039922]: github.com/seaweedfs/seaweedfs/weed/storage/needle.(*Needle).ReadNeedleMeta(0xc02ccbd790, {0x293ddc0, 0xc00a3671c0}, 0x35f50c898, 0x40004c, 0x3)
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/github/workspace/weed/storage/needle/needle_read_page.go:84 +0x11c
Aug 18 05:34:21  seaweedfs-volume[3039922]: github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).readNeedle(0xc0038fdd40, 0xc02ccbd790, 0xc02cd35100, 0xc023767310)
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/github/workspace/weed/storage/volume_read.go:44 +0x338
Aug 18 05:34:21  seaweedfs-volume[3039922]: github.com/seaweedfs/seaweedfs/weed/storage.(*Store).ReadVolumeNeedle(0xc00022dd00?, 0x0?, 0xb?, 0x4?, 0xc02b33d74a?)
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/github/workspace/weed/storage/store.go:383 +0x49
Aug 18 05:34:21  seaweedfs-volume[3039922]: github.com/seaweedfs/seaweedfs/weed/server.(*VolumeServer).GetOrHeadHandler(0xc000893400, {0x2932590, 0xc02b7002a0}, 0xc00022dd00)
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/github/workspace/weed/server/volume_server_handlers_read.go:130 +0x52f
Aug 18 05:34:21  seaweedfs-volume[3039922]: github.com/seaweedfs/seaweedfs/weed/server.(*VolumeServer).privateStoreHandler(0xc000893400, {0x2932590, 0xc02b7002a0}, 0xc00022dd00)
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/github/workspace/weed/server/volume_server_handlers.go:59 +0x105d
Aug 18 05:34:21  seaweedfs-volume[3039922]: net/http.HandlerFunc.ServeHTTP(0xc02cd64af0?, {0x2932590?, 0xc02b7002a0?}, 0x0?)
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/usr/local/go/src/net/http/server.go:2109 +0x2f
Aug 18 05:34:21  seaweedfs-volume[3039922]: net/http.(*ServeMux).ServeHTTP(0xc02b33d75b?, {0x2932590, 0xc02b7002a0}, 0xc00022dd00)
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/usr/local/go/src/net/http/server.go:2487 +0x149
Aug 18 05:34:21  seaweedfs-volume[3039922]: net/http.serverHandler.ServeHTTP({0xc02cd739e0?}, {0x2932590, 0xc02b7002a0}, 0xc00022dd00)
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/usr/local/go/src/net/http/server.go:2947 +0x30c
Aug 18 05:34:21  seaweedfs-volume[3039922]: net/http.(*conn).serve(0xc02ca35220, {0x29343c8, 0xc02617eff0})
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/usr/local/go/src/net/http/server.go:1991 +0x607
Aug 18 05:34:21  seaweedfs-volume[3039922]: created by net/http.(*Server).Serve
Aug 18 05:34:21  seaweedfs-volume[3039922]: #011/usr/local/go/src/net/http/server.go:3102 +0x4db
```

**Comment by LuckyFrost** [comment]
[kill3volume_2.txt](https://github.com/seaweedfs/seaweedfs/files/9418991/kill3volume_2.txt)

**Comment by LuckyFrost** [comment]
After starting the server there are a number of such errors
```
Aug 24 14:57:58 seaweedfs-volume[2415351]: 2022/08/24 14:57:58 http: panic serving 192.168.0.4:41124: runtime error: makeslice: len out of range
Aug 24 14:57:58 seaweedfs-volume[2415351]: goroutine 26735 [running]:
Aug 24 14:57:58 seaweedfs-volume[2415351]: net/http.(*conn).serve.func1()
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/usr/local/go/src/net/http/server.go:1850 +0xbf
Aug 24 14:57:58 seaweedfs-volume[2415351]: panic({0x1fa05a0, 0x290adf0})
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/usr/local/go/src/runtime/panic.go:890 +0x262
Aug 24 14:57:58 seaweedfs-volume[2415351]: github.com/seaweedfs/seaweedfs/weed/storage/needle.(*Needle).ReadNeedleMeta(0xc04c8e6820, {0x2932870, 0xc000cd1600}, 0x1afa96f28,
 0x40004c, 0x3)
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/github/workspace/weed/storage/needle/needle_read_page.go:84 +0x11c
Aug 24 14:57:58 seaweedfs-volume[2415351]: github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).readNeedle(0xc00dbf2b40, 0xc04c8e6820, 0xc04c8ccc98, 0xc00c985300)
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/github/workspace/weed/storage/volume_read.go:44 +0x338
Aug 24 14:57:58 seaweedfs-volume[2415351]: github.com/seaweedfs/seaweedfs/weed/storage.(*Store).ReadVolumeNeedle(0xc04e51ec00?, 0x0?, 0xb?, 0x4?, 0xc04c8c138a?)
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/github/workspace/weed/storage/store.go:383 +0x49
Aug 24 14:57:58 seaweedfs-volume[2415351]: github.com/seaweedfs/seaweedfs/weed/server.(*VolumeServer).GetOrHeadHandler(0xc000a79200, {0x2927050, 0xc04c8d3880}, 0xc04e51ec00
)
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/github/workspace/weed/server/volume_server_handlers_read.go:130 +0x52f
Aug 24 14:57:58 seaweedfs-volume[2415351]: github.com/seaweedfs/seaweedfs/weed/server.(*VolumeServer).privateStoreHandler(0xc000a79200, {0x2927050, 0xc04c8d3880}, 0xc04e51e
c00)
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/github/workspace/weed/server/volume_server_handlers.go:59 +0x1085
Aug 24 14:57:58 seaweedfs-volume[2415351]: net/http.HandlerFunc.ServeHTTP(0xc00c985af0?, {0x2927050?, 0xc04c8d3880?}, 0x0?)
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/usr/local/go/src/net/http/server.go:2109 +0x2f
Aug 24 14:57:58 seaweedfs-volume[2415351]: net/http.(*ServeMux).ServeHTTP(0xc04c8c139b?, {0x2927050, 0xc04c8d3880}, 0xc04e51ec00)
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/usr/local/go/src/net/http/server.go:2487 +0x149
Aug 24 14:57:58 seaweedfs-volume[2415351]: net/http.serverHandler.ServeHTTP({0xc048c4c720?}, {0x2927050, 0xc04c8d3880}, 0xc04e51ec00)
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/usr/local/go/src/net/http/server.go:2947 +0x30c
Aug 24 14:57:58 seaweedfs-volume[2415351]: net/http.(*conn).serve(0xc0184ce1e0, {0x2928e88, 0xc01890fad0})
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/usr/local/go/src/net/http/server.go:1991 +0x607
Aug 24 14:57:58 seaweedfs-volume[2415351]: created by net/http.(*Server).Serve
Aug 24 14:57:58 seaweedfs-volume[2415351]: #011/usr/local/go/src/net/http/server.go:3102 +0x4db
```

**Comment by chrislusf** [comment]
when this happens, it often means the `.idx` and `.dat` files are out of sync. The volume server is using some `.idx` copy not for current `.dat` file.

I check all code and did fix some bugs related using one shared `-dir.idx` folder and multiple `-dir` folders. But those issues are only related to erasure coding only.

**Comment by LuckyFrost** [comment]
EC has never been used and probably could not even be used - there are only 4  volume servers in this installation.

The volume server is still not responding to anything and I still don't understand how to hotfix the problem...

**Comment by chrislusf** [comment]
I understand this is not a quick solution, and you may need to has some scripts to do this with thousands of volume servers.

To fix current issues, one thing you can do is to stop using `-dir.idx` folder for now, and try to generate `.idx` files with `weed fix` command directly if in doubt which `.idx` file to use.
